### ISSUE TITLE
Change number of genes for filter_genes as a pipeline input parameter.

### ISSUE THREAD

**Issue by atuldeshpande** [break-through-cancer/btc-spatial-pipelines#36]
https://github.com/break-through-cancer/btc-spatial-pipelines/blob/0f39feb1656e9f94545a2ff6ffb60deae414581e/workflows/spatial.nf#L107

**Comment by dimalvovs** [comment]
This will need some refactoring of the pipeline:

- [ ] create "filter genes" parameter in the "deconvolution settings" , when empty do not filter any genes
- [ ] move "bleeding correction" boolean to the "deconvolution settings" 
- [ ] convert from h5ad and plug BAYESTME_BLEEDING_CORRECTION into CoGAPS
- [ ] in addition, fix #43

**Comment by dimalvovs** [comment]
*setting "filter genes" to some very large number such as 99999 should work too, as the number of genes to keep [is determined](https://github.com/tansey-lab/bayestme/blob/1b8bc17246e9f5a6d599888acf6b1d617dcec1cd/src/bayestme/gene_filtering.py#L25) as min(requested genes to keep, number of genes in the dataset), with the only moderate disadvantage that standard deviations will need to be computed. @jeffquinn-msk OK with that?
